"""Generate the manuscript tables from their machine-readable sources.

Writes LaTeX table rows and results_summary.json from the result files under
reproduce/.  No number in the paper is transcribed by hand: this module reads
the result CSVs written by the study drivers and emits LaTeX tables into
`outputs/generated/`, together with `outputs/results_summary.json`.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT = Path(__file__).resolve().parents[2]
REV = PROJECT / "reproduce"
GEN = PROJECT / "outputs" / "generated"
E24 = REV / "table_s3" / "."

HEADER = (
    "%% Generated by reproduce/shared/build_tables.py.\n"
    "%% Source: %s\n"
    "%% Do not edit manually.\n"
)

CASE_DISPLAY = {
    "orthogonal_duct": "Orthogonal duct",
    "skewed_duct": "Skewed duct",
    "bentheimer_crop": "Bentheimer crop",
    "thin_wall": "Thin wall",
    "narrow_throat": "Narrow throat",
    "maze": "Maze",
    "berea_heldout_64": "Berea $64^3$",
}


def fmt(value, digits=2, dash="--"):
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return dash
    return ("%%.%df" % digits) % value


STATUS_DISPLAY = {
    "converged": "converged",
    "not_converged": "not converged",
    "non_positive_velocity_diagonal": "\\(A\\) diagonal not positive",
    "non_positive_schur_diagonal": "Schur diagonal not positive",
}


def status_text(value):
    return STATUS_DISPLAY.get(str(value), str(value).replace("_", " "))


def sci(value, digits=2):
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return "--"
    exponent = int(math.floor(math.log10(abs(value)))) if value else 0
    mantissa = value / (10.0 ** exponent)
    return "\\(%.*f\\times10^{%d}\\)" % (digits, mantissa, exponent)


def slope(x, y, last=None):
    x = np.log(np.asarray(x, dtype=float))
    y = np.log(np.asarray(y, dtype=float))
    if last:
        x, y = x[-last:], y[-last:]
    coefficients = np.polyfit(x, y, 1)
    residual = np.corrcoef(x, y)[0, 1] ** 2 if len(x) > 2 else float("nan")
    return float(coefficients[0]), float(residual)


def ladder_frame(root=None):
    """Assemble the refinement ladder from the per-run records.

    The driver writes its summary CSV only when the whole sweep finishes, so a
    partially finished sweep leaves a stale CSV on disk.  The per-run `row.json`
    files are written as each level completes and are therefore the authoritative
    source; reading them removes the possibility of building a table from an
    older summary.
    """
    root = Path(root or (REV / "figure_06/refinement" / "runs"))
    records = []
    for path in sorted(root.glob("*/*/row.json")):
        records.append(json.loads(path.read_text(encoding="utf-8")))
    if not records:
        return None
    frame = pd.DataFrame(records)
    order = ["orthogonal_duct", "skewed_duct", "bentheimer_crop"]
    frame["_case_order"] = frame["case"].map(
        {name: index for index, name in enumerate(order)}
    ).fillna(len(order))
    return frame.sort_values(["_case_order", "level_index"]).drop(columns="_case_order")


# --------------------------------------------------------------------------
def controlled_refinement(summary):
    df = ladder_frame()
    if df is None:
        return None
    path = REV / "figure_06/refinement" / "runs"
    signed = pd.read_csv(REV / "supplementary/s2_discretization" / "permeability_readouts.csv")
    signed = signed[signed["K_method_flux"].notna()].copy()
    signed["e_K_signed_percent"] = 100 * (signed["K_method_flux"] - signed["K_reference_stored"]) / signed["K_reference_stored"].abs()
    df = df.merge(signed[["case", "N_cv", "e_K_signed_percent"]], on=["case", "N_cv"], validate="one_to_one")
    if len(df) != 18:
        raise ValueError("Incomplete controlled-refinement signed join")
    df.to_csv(REV / "figure_06/refinement" / "mask_fps_refinement_from_runs.csv", index=False)
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Controlled prescribed-site refinement on fixed voxel masks. "
        "Sites come from deterministic graph farthest-point sampling over every "
        "pore voxel; the mask, reference field, boundary convention, viscosity, "
        "forcing, trace basis, stabilization and solver are identical across all "
        "levels of a case. \\(H_g/h\\) is the graph fill distance in pore-graph "
        "edges and \\(q_S/h\\) the minimum site separation. \\(e_p\\) is omitted "
        "for the orthogonal duct, whose exact pressure perturbation is constant "
        "so that the metric has a round-off denominator. The permeability column reports the signed discrepancy \\(e_K^{\\rm s}\\). A dagger marks the two Bentheimer entries smaller than the 0.868 percent readout offset; these are unresolved as accuracy statements.}",
        "\\label{tab:controlled-refinement}", "\\begingroup", "\\scriptsize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}llrrrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & KKT dim & \\(H_g/h\\) & \\(q_S/h\\) & "
        "\\(e_K^{\\rm s}\\) (\\%) & \\(e_\\phi\\) (\\%) & \\(e_u\\) (\\%) & \\(e_p\\) (\\%) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            degenerate = case == "orthogonal_duct"
            lines.append(
                "%s & %s & %d & %d & %s & %s & %s & %s & %s & %s \\\\" % (
                    CASE_DISPLAY.get(case, case), row["level_label"].split("_")[0],
                    int(row["N_cv"]), int(row["N_system"]),
                    fmt(row["h_S_over_h"], 0), fmt(row["q_S_over_h"], 1),
                    (fmt(row["e_K_signed_percent"], 2) + (r"\(^{\dagger}\)" if case == "bentheimer_crop" and int(row["N_cv"]) in (400, 3200) else "")), fmt(row["e_phi_percent"], 2),
                    fmt(row["e_u_percent"], 2),
                    "--" if degenerate else fmt(row["e_p_percent"], 2),
                )
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}"]
    if any("resizebox" in line for line in lines):
        lines.append("}")
    lines += ["\\endgroup", "\\end{table}"]
    (GEN / "controlled_refinement_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )

    slopes = {}
    for case, block in df.groupby("case", sort=False):
        block = block.sort_values("level_index")
        entry = {}
        for metric in ["e_K_percent", "e_phi_percent", "e_u_percent", "e_p_percent"]:
            values = block[metric].values
            if not np.all(np.isfinite(values)) or np.any(values <= 0):
                continue
            for name, count in (("all_levels", None), ("last_three", 3)):
                a, r2 = slope(block["N_cv"].values ** (1.0 / 3.0), values, count)
                entry["%s__vs_mean_cell_size__%s" % (metric, name)] = {
                    "slope": -a, "r_squared": r2
                }
        entry["levels"] = block["level_label"].tolist()
        entry["h_S_over_h"] = block["h_S_over_h"].tolist()
        entry["q_S_over_h"] = block["q_S_over_h"].tolist()
        entry["e_u_percent"] = block["e_u_percent"].tolist()
        entry["e_phi_percent"] = block["e_phi_percent"].tolist()
        entry["e_K_percent"] = block["e_K_percent"].tolist()
        entry["e_K_signed_percent"] = block["e_K_signed_percent"].tolist()
        entry["e_p_percent"] = block["e_p_percent"].tolist()
        entry["N_cv"] = block["N_cv"].tolist()
        entry["N_system"] = block["N_system"].tolist()
        slopes[case] = entry
    summary["controlled_refinement"] = slopes
    return df


def mass_backward_error(summary):
    path = REV / "supplementary/s3_verification" / "mass_backward_error.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    summary["mass_backward_error"] = {
        "rows": int(len(df)),
        "eta_m_upper_bound_max": float(df["eta_m_aggregate_upper_bound"].max()),
        "eta_m_upper_bound_min": float(df["eta_m_aggregate_upper_bound"].min()),
        "mass_inf_per_volume_max": float(df["mass_inf_per_volume_archived"].max()),
        "mass_inf_per_volume_min": float(df["mass_inf_per_volume_archived"].min()),
        "definition": ("upper bound: the denominator uses the aggregate stored-edge "
                       "throughput, which cannot exceed the facelet sum"),
        "records": df.to_dict(orient="records"),
    }
    return df


def manufactured(summary):
    path = REV / "table_03" / "manufactured_stokes.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    record = {}
    for functional, block in df.groupby("load_functional"):
        block = block.sort_values("sites_per_side")
        entry = {
            "levels": block["level_label"].tolist(),
            "voxels_per_side": block["voxels_per_side"].tolist(),
            "sites_per_side": block["sites_per_side"].tolist(),
            "N_cv": block["N_cv"].tolist(),
            "N_system": block["N_system"].tolist(),
            "nnz_A": block["nnz_A"].tolist(),
            "nnz_D": block["nnz_D"].tolist(),
            "e_u_percent": block["e_u_percent"].tolist(),
            "e_p_percent": block["e_p_percent"].tolist(),
            "e_phi_percent": block["e_phi_percent"].tolist(),
            "mass_backward_error_dimensionless":
                block["mass_backward_error_dimensionless"].tolist(),
        }
        inverse_H = 1.0 / block["H_over_L"].values
        for metric in ["e_u_percent", "e_p_percent", "e_phi_percent"]:
            for name, count in (("all_levels", None), ("last_three", 3)):
                a, r2 = slope(inverse_H, block[metric].values, count)
                entry["%s__slope__%s" % (metric, name)] = {"slope": -a, "r_squared": r2}
        record[functional] = entry
    summary["manufactured_stokes"] = record
    return df


def manufactured_fixed_h(summary):
    path = REV / "table_03" / "fixed_h" / "manufactured_stokes.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path).sort_values("sites_per_side")
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Prescribed-site refinement at \\emph{fixed} voxel resolution "
        "on the manufactured problem: \\(N=48\\) throughout, so the image never "
        "changes and only the site lattice does. The fitted slopes are not "
        "comparable with those of Table~\\ref{tab:manufactured-convergence}, "
        "because here \\(H/h\\) falls from 12 to 2 as well as \\(H/L\\); the two "
        "sequences answer different questions and both are reported.}",
        "\\label{tab:manufactured-fixed-h}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}rrrrrrrr@{}}", "\\toprule",
        "\\(m\\) & \\(H/h\\) & \\(L/H\\) & \\(N_c\\) & KKT dim & "
        "\\(e_u\\) (\\%) & \\(e_p\\) (\\%) & \\(e_\\phi\\) (\\%) \\\\",
        "\\midrule",
    ]
    for _, row in df.iterrows():
        lines.append("%d & %s & %s & %d & %d & %s & %s & %s \\\\" % (
            int(row["sites_per_side"]), fmt(row["H_over_h"], 0),
            fmt(1.0 / row["H_over_L"], 0), int(row["N_cv"]), int(row["N_system"]),
            fmt(row["e_u_percent"], 3), fmt(row["e_p_percent"], 3),
            fmt(row["e_phi_percent"], 3),
        ))
    inverse_H = 1.0 / df["H_over_L"].values
    slopes = {}
    row_all, row_last = [], []
    for metric in ["e_u_percent", "e_p_percent", "e_phi_percent"]:
        a, r2 = slope(inverse_H, df[metric].values)
        b, _ = slope(inverse_H, df[metric].values, 3)
        slopes[metric] = {"all_levels": {"slope": -a, "r_squared": r2},
                          "last_three": {"slope": -b}}
        row_all.append(fmt(-a, 2))
        row_last.append(fmt(-b, 2))
    lines += [
        "\\midrule",
        "\\multicolumn{5}{@{}l}{fitted slope, all six levels} & " + " & ".join(row_all) + " \\\\",
        "\\multicolumn{5}{@{}l}{fitted slope, finest three levels} & " + " & ".join(row_last) + " \\\\",
        "\\bottomrule", "\\end{tabular}", "\\endgroup", "\\end{table}",
    ]
    (GEN / "manufactured_fixed_h_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["manufactured_fixed_h"] = {
        "sites_per_side": df["sites_per_side"].tolist(),
        "H_over_h": df["H_over_h"].tolist(),
        "N_cv": df["N_cv"].tolist(),
        "N_system": df["N_system"].tolist(),
        "e_u_percent": df["e_u_percent"].tolist(),
        "e_p_percent": df["e_p_percent"].tolist(),
        "e_phi_percent": df["e_phi_percent"].tolist(),
        "slopes": slopes,
    }
    return df


def fibrous(summary):
    path = REV / "supplementary/s3_verification" / "stabilization_sweep__fibrous_filter_proxy.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path).sort_values("tau")
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Residual-stabilization sensitivity on the fibrous "
        "high-wall-contact case. \\(\\tau=1\\) is the retained rule of "
        "Eq.~\\eqref{eq:forward-local-bilinear-form}; the assembly used to form "
        "\\(A(\\tau)=A_{\\mathrm{cons}}+\\tau A_{\\mathrm{stab}}\\) reproduces the "
        "production velocity, divergence and load matrices bitwise at "
        "\\(\\tau=1\\). \\(\\eta_m\\) is the dimensionless mass-balance backward "
        "error of Eq.~\\eqref{eq:mass-backward-error}.}",
        "\\label{tab:fibrous-stabilization}", "\\begingroup", "\\scriptsize",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\begin{tabular}{@{}rlrrrrrr@{}}", "\\toprule",
        "\\(\\tau\\) & MINRES & iters & rel. resid. & \\(e_K\\) (\\%) & "
        "\\(e_u\\) (\\%) & \\(e_p\\) (\\%) & \\(\\eta_m\\) \\\\",
        "\\midrule",
    ]
    for _, row in df.iterrows():
        lines.append(
            "%s & %s & %s & %s & %s & %s & %s & %s \\\\" % (
                ("\\textbf{%s}" % fmt(row["tau"], 2)) if abs(row["tau"] - 1.0) < 1e-12
                else fmt(row["tau"], 2),
                status_text(row.get("solver_status", "--")),
                "%d" % row["linear_solver_iterations"]
                if pd.notna(row.get("linear_solver_iterations")) else "--",
                sci(row.get("linear_solver_relative_residual")),
                fmt(row.get("e_K_percent"), 2), fmt(row.get("e_u_percent"), 2),
                fmt(row.get("e_p_percent"), 2),
                sci(row.get("mass_backward_error_dimensionless")),
            )
        )
    lines += ["\\bottomrule", "\\end{tabular}", ("}" if any("resizebox" in line for line in lines) else ""), "\\endgroup", "\\end{table}"]
    (GEN / "fibrous_stabilization_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["fibrous_stabilization"] = df.to_dict(orient="list")
    return df


def euclidean(summary):
    path = REV / "figure_01" / "euclidean_vs_geodesic_ownership.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Voxel-restricted Euclidean ownership against graph-geodesic "
        "ownership on identical pore masks and identical prescribed sites, with "
        "the same lexicographic tie rule. Disconnected cells are owner regions "
        "with more than one six-connected component; orphan voxels are pore "
        "voxels not face-connected to their own site inside their owner region; "
        "the detour ratio is the graph-geodesic distance to the assigned site "
        "divided by the \\(L^1\\) distance to the same site. Both ratios are "
        "measured; obstacles can make either exceed one.}",
        "\\label{tab:euclidean-ownership}", "\\begingroup", "\\scriptsize", "\\resizebox{\\textwidth}{!}{%",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}lrrrrrrrr@{}}", "\\toprule",
        " & & \\multicolumn{4}{c}{Euclidean ownership} & "
        "\\multicolumn{3}{c}{Graph-geodesic} \\\\",
        "\\cmidrule(lr){3-6}\\cmidrule(lr){7-9}",
        "Case & \\(N_c\\) & disc. cells (\\%) & orphan vox. (\\%) & "
        "max comp. & max detour & disc. cells & orphan vox. & max detour \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.sort_values("N_sites").iterrows():
            lines.append(
                "%s & %d & %s & %s & %d & %s & %d & %d & %s \\\\" % (
                    CASE_DISPLAY.get(case, case), int(row["N_sites"]),
                    fmt(100.0 * row["euclidean__cells_disconnected_fraction"], 2),
                    fmt(100.0 * row["euclidean__orphan_voxel_fraction"], 3),
                    int(row["euclidean__max_components_in_one_cell"]),
                    fmt(row["euclidean__owner_detour_ratio_max"], 1),
                    int(row["geodesic__cells_disconnected"]),
                    int(row["geodesic__orphan_voxels"]),
                    fmt(row["geodesic__owner_detour_ratio_max"], 2),
                )
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}"]
    if any("resizebox" in line for line in lines):
        lines.append("}")
    lines += ["\\endgroup", "\\end{table}"]
    (GEN / "euclidean_ownership_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["euclidean_ownership"] = {
        "max_disconnected_cell_fraction_percent":
            float(100.0 * df["euclidean__cells_disconnected_fraction"].max()),
        "min_disconnected_cell_fraction_percent":
            float(100.0 * df["euclidean__cells_disconnected_fraction"].min()),
        "max_orphan_voxel_fraction_percent":
            float(100.0 * df["euclidean__orphan_voxel_fraction"].max()),
        "max_components_in_one_cell": int(df["euclidean__max_components_in_one_cell"].max()),
        "max_detour_ratio": float(df["euclidean__owner_detour_ratio_max"].max()),
        "max_geodesic_detour_ratio": float(df["geodesic__owner_detour_ratio_max"].max()),
        "geodesic_disconnected_cells_total": int(df["geodesic__cells_disconnected"].sum()),
        "geodesic_orphan_voxels_total": int(df["geodesic__orphan_voxels"].sum()),
        "rows": int(len(df)),
        "cases": sorted(df["case"].unique().tolist()),
    }
    return df


def site_sources(summary):
    path = E24 / "site_rule_comparison.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    label = {
        "proposed": "Trajectory support",
        "mask_graph_fps": "Graph FPS (geometry only)",
        "connected_block_agglomeration": "Connected block agglomeration",
        "euclidean_partition_with_deterministic_connectivity_repair":
            "Euclidean partition (repaired)",
    }
    order = list(label)
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Prescribed-site rules and one alternative partition at matched "
        "algebraic size. Rows within a case and budget agree on \\(N_{\\rm "
        "system}\\) to within ten per cent. Selection of the geometry-only rules "
        "is result-blind: the site count and the block family are chosen by "
        "bisection on \\(N_{\\rm system}\\) alone. \\(\\beta_h\\) is the discrete "
        "pressure-coupling proxy of Section~\\ref{sec:stokes-admissibility}, not "
        "an inf--sup constant. \\(e_p\\) is not interpretable for the orthogonal "
        "duct and that case is not included here. The permeability column is the signed discrepancy \\(e_K^{\\rm s}\\).}",
        "\\label{tab:site-source-baselines}", "\\begingroup", "\\scriptsize", "\\resizebox{\\textwidth}{!}{%",
        "\\setlength{\\tabcolsep}{3.5pt}",
        "\\begin{tabular}{@{}llrrrrrrr@{}}", "\\toprule",
        "Case / budget & Site or partition rule & \\(N_c\\) & KKT dim & "
        "\\(e_K^{\\rm s}\\) (\\%) & \\(e_\\phi\\) (\\%) & \\(e_u\\) (\\%) & "
        "\\(e_p\\) (\\%) & \\(\\beta_h\\) \\\\",
        "\\midrule",
    ]
    for (case, budget), block in df.groupby(["case", "budget_label"], sort=False):
        first = True
        block = block.set_index("method_id").reindex(
            [m for m in order if m in set(block["method_id"])]
        ).reset_index()
        for _, row in block.iterrows():
            lines.append(
                "%s & %s & %d & %d & %s & %s & %s & %s & %s \\\\" % (
                    ("%s, %s" % (CASE_DISPLAY.get(case, case), budget)) if first else "",
                    label.get(row["method_id"], row["method_id"]),
                    int(row["N_cv"]), int(row["N_system"]),
                    fmt(row["e_K_signed_percent"], 2), fmt(row["e_phi_percent"], 2),
                    fmt(row["e_u_percent"], 2), fmt(row["e_p_percent"], 2),
                    sci(row["beta_h"]) if pd.notna(row["beta_h"]) else "--",
                )
            )
            first = False
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}"]
    if any("resizebox" in line for line in lines):
        lines.append("}")
    lines += ["\\endgroup", "\\end{table}"]
    (GEN / "site_source_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["site_source_baselines"] = df[
        ["case", "budget_label", "method_id", "N_cv", "N_system",
         "e_K_signed_percent", "e_phi_percent", "e_u_percent", "e_p_percent", "beta_h",
         "schur_condition_proxy", "admissibility_status"]
    ].to_dict(orient="records")
    return df


def kernel_exact(summary):
    path = REV / "supplementary/s2_discretization" / "kernel_exact.json"
    if not path.exists():
        return None
    records = json.loads(path.read_text(encoding="utf-8"))
    df = pd.DataFrame(records)
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{The kernel of the viscous block, decided exactly by the "
        "reduction of Proposition~\\ref{prop:viscous-kernel}. \\(M\\) has "
        "\\(6N_c\\) columns, three rows per internal facelet and three per wall "
        "facelet. The rank tolerance is \\(\\max(m,n)\\,\\epsilon_{\\mathrm{mach}}\\) "
        "times the largest entry of \\(M^{\\top}M\\).}",
        "\\label{tab:kernel-exact}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}llrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & \\(6N_c\\) & rows of \\(M\\) & "
        "\\(\\lambda_{\\min}(M^{\\top}M)\\) & tolerance & "
        "\\(\\dim\\ker A\\) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            lines.append(
                "%s & %s & %d & %d & %d & %s & %s & %d \\\\" % (
                    CASE_DISPLAY.get(case, case), row["level_label"].split("_")[0],
                    int(row["N_cv"]), int(row["rigid_unknowns"]),
                    int(row["constraint_rows"]),
                    sci(row["smallest_eigenvalues_MtM"][0]),
                    sci(row["rank_tolerance"]), int(row["kernel_dimension"]),
                )
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "kernel_exact_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["kernel_exact"] = {
        "rows": int(len(df)),
        "trivial_rows": int(df["ker_A_trivial"].sum()),
        "lambda_min_max": float(max(r["smallest_eigenvalues_MtM"][0] for r in records)),
        "lambda_min_min": float(min(r["smallest_eigenvalues_MtM"][0] for r in records)),
        "worst_margin_over_tolerance": float(min(
            r["smallest_eigenvalues_MtM"][0] / r["rank_tolerance"] for r in records)),
        "records": [{k: v for k, v in r.items() if k != "smallest_eigenvalues_MtM"}
                    for r in records],
    }
    return df


def stability_ladder(summary):
    path = REV / "supplementary/s2_discretization" / "stability_along_refinement.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    order = {"orthogonal_duct": 0, "skewed_duct": 1, "bentheimer_crop": 2}
    df = df.assign(_o=df["case"].map(order).fillna(9)).sort_values(["_o", "N_cv"])
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Discrete pressure coupling along the controlled refinement "
        "families. \\(\\beta_h\\) is the pressure-coupling proxy of "
        "Section~\\ref{sec:stokes-admissibility} and not an inf--sup constant; it "
        "is reported so that its behaviour under refinement is visible, which is "
        "what the analysis in this paper does not supply.}",
        "\\label{tab:stability-ladder}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}llrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & \\(H_g/h\\) & rank defect & "
        "\\(\\beta_h\\) & condition proxy & \\(e_u\\) (\\%) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            lines.append("%s & %s & %d & %s & %d & %s & %s & %s \\\\" % (
                CASE_DISPLAY.get(case, case), str(row["level_label"]).split("_")[0],
                int(row["N_cv"]), fmt(row.get("h_S_over_h"), 0),
                int(row["rank_defect_estimate_after_gauge"]),
                sci(row["beta_h"]), sci(row["schur_condition_proxy"]),
                fmt(row["e_u_percent"], 2),
            ))
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "stability_ladder_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    record = {"rows": int(len(df)),
              "families": int(df["case"].nunique()),
              "rank_defect_max": int(df["rank_defect_estimate_after_gauge"].max()),
              "e_u_monotone_families": int(sum(
                  bool((block.sort_values("N_cv")["e_u_percent"].diff().dropna() < 0).all())
                  for _, block in df.groupby("case"))),
              "beta_h_min": float(df["beta_h"].min()),
              "beta_h_max": float(df["beta_h"].max()),
              "condition_proxy_min": float(df["schur_condition_proxy"].min()),
              "condition_proxy_max": float(df["schur_condition_proxy"].max())}
    for case, block in df.groupby("case"):
        block = block.sort_values("N_cv")
        record[case] = {
            "levels": block["level_label"].tolist(),
            "N_cv": block["N_cv"].tolist(),
            "beta_h": block["beta_h"].tolist(),
            "schur_condition_proxy": block["schur_condition_proxy"].tolist(),
            "beta_h_finest_over_coarsest":
                float(block["beta_h"].iloc[-1] / block["beta_h"].iloc[0]),
            "condition_proxy_growth_factor":
                float(block["schur_condition_proxy"].iloc[-1]
                      / block["schur_condition_proxy"].iloc[0]),
            "e_u_percent": block["e_u_percent"].tolist(),
            "e_u_coarsest": float(block["e_u_percent"].iloc[0]),
            "e_u_finest": float(block["e_u_percent"].iloc[-1]),
            "e_u_monotone_decreasing": bool(
                (block["e_u_percent"].diff().dropna() < 0).all()),
            "H_over_h_coarsest": float(block["h_S_over_h"].iloc[0]),
            "H_over_h_finest": float(block["h_S_over_h"].iloc[-1]),
        }
    summary["stability_along_refinement"] = record
    return df


def stability(summary):
    path = E24 / "stability_audit.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    summary["stokes_admissibility"] = {
        "rows": int(len(df)),
        "rank_defect_after_gauge_max": int(df["rank_defect_estimate_after_gauge"].max()),
        "rank_defect_after_gauge_nonzero_rows": int(
            (df["rank_defect_estimate_after_gauge"] != 0).sum()
        ),
        "beta_h_min": float(df["beta_h"].min()),
        "beta_h_max": float(df["beta_h"].max()),
        "schur_condition_proxy_min": float(df["schur_condition_proxy"].min()),
        "schur_condition_proxy_max": float(df["schur_condition_proxy"].max()),
        "kkt_symmetry_defect_max": float(df["kkt_symmetry_defect"].max()),
        "spectral_status_values": sorted(df["spectral_status"].unique().tolist()),
    }
    return df


def stabilization_scale(summary):
    rows = []
    for name in ("voxel_refinement", "stabilization_scaling_wide"):
        path = REV / "figure_06" / name / "stabilization_scaling.csv"
        if path.exists():
            rows.append(pd.read_csv(path))
    if not rows:
        return None
    df = pd.concat(rows, ignore_index=True).drop_duplicates(
        subset=["voxels_per_side", "sites_per_side", "tau"], keep="last"
    )
    fixed = df[df.sites_per_side == 4].copy()
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{The control-volume-to-voxel ratio \\(H/h\\) is a second "
        "resolution parameter. All rows share the same cell topology "
        "(\\(4^3=64\\) cells), the same relative cell size \\(H/L=1/4\\) and the "
        "same trace space (KKT dimension 1359); only the voxel resolution "
        "changes. For each \\(H/h\\) the best velocity error over the swept "
        "stabilization multiplier is reported together with the \\(\\tau\\) that "
        "attains it.}",
        "\\label{tab:stabilization-scale}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}rrrrrrr@{}}", "\\toprule",
        "\\(N\\) & \\(H/h\\) & \\(e_u\\) at \\(\\tau=1\\) (\\%) & "
        "best \\(e_u\\) (\\%) & at \\(\\tau=\\) & "
        "\\(e_p\\) at \\(\\tau=1\\) (\\%) & \\(e_\\phi\\) at \\(\\tau=1\\) (\\%) \\\\",
        "\\midrule",
    ]
    scale = {}
    for n, block in fixed.groupby("voxels_per_side"):
        block = block.sort_values("tau")
        at_one = block[np.isclose(block.tau, 1.0)]
        best = block.loc[block["e_u_percent"].idxmin()]
        lines.append(
            "%d & %s & %s & %s & %s & %s & %s \\\\" % (
                int(n), fmt(block["H_over_h"].iloc[0], 0),
                fmt(at_one["e_u_percent"].iloc[0], 2) if len(at_one) else "--",
                fmt(best["e_u_percent"], 2), fmt(best["tau"], 3),
                fmt(at_one["e_p_percent"].iloc[0], 2) if len(at_one) else "--",
                fmt(at_one["e_phi_percent"].iloc[0], 2) if len(at_one) else "--",
            )
        )
        scale[int(n)] = {
            "H_over_h": float(block["H_over_h"].iloc[0]),
            "tau_swept": block["tau"].tolist(),
            "e_u_percent": block["e_u_percent"].tolist(),
            "best_e_u_percent": float(best["e_u_percent"]),
            "best_tau": float(best["tau"]),
            "tau_at_boundary_of_sweep": bool(
                best["tau"] in (block["tau"].min(), block["tau"].max())
            ),
        }
    lines += ["\\bottomrule", "\\end{tabular}", ("}" if any("resizebox" in line for line in lines) else ""), "\\endgroup", "\\end{table}"]
    (GEN / "stabilization_scale_table.tex").write_text(
        HEADER % "reproduce/figure_06/voxel_refinement/"
        + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["stabilization_scale"] = scale
    return df


def cost(summary):
    path = REV / "supplementary/s4_cost" / "cost_and_sizes.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path).sort_values(["case", "N_cv"])
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Algebraic size, memory and cost of the controlled refinement "
        "families. \\(\\mathrm{nnz}(A)\\) is what the solver stores, recovered "
        "exactly from the archived storage record and checked against a full "
        "production assembly; the structural union of the per-cell dense blocks "
        "is larger by the fraction given. The reference count is \\(4N_f\\), the "
        "image-resolved solver's own unknowns on the same mask. "
        "\\(T_{\\rm cold}\\) is ownership, facelets, trace basis, assembly, "
        "preconditioner and one solve; \\(T_{\\rm query}\\) is a further solve on "
        "the same complex.}",
        "\\label{tab:end-to-end-cost}", "\\begingroup", "\\scriptsize", "\\resizebox{\\textwidth}{!}{%",
        "\\setlength{\\tabcolsep}{3.5pt}",
        "\\begin{tabular}{@{}llrrrrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & KKT dim & \\(\\mathrm{nnz}(A)\\) & "
        "\\(\\mathrm{nnz}(D)\\) & struct.\\ zero & mem (MiB) & "
        "KKT\\(/4N_f\\) & \\(T_{\\rm cold}\\) (s) & \\(T_{\\rm query}\\) (s) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            lines.append(
                "%s & %s & %d & %d & %s & %s & %s & %s & %s & %s & %s \\\\" % (
                    CASE_DISPLAY.get(case, case), row["level_label"].split("_")[0],
                    int(row["N_cv"]), int(row["N_system"]),
                    "{:,}".format(int(row["nnz_A"])).replace(",", "\\,"),
                    "{:,}".format(int(row["nnz_D"])).replace(",", "\\,"),
                    fmt(100.0 * row["nnz_A_structural_zero_fraction"], 0) + "\\%",
                    fmt(row["factor_memory_MiB"], 0),
                    fmt(row["KKT_over_reference_unknowns"], 3),
                    fmt(row["T_cold_s"], 0), fmt(row["T_query_s"], 0),
                )
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}"]
    if any("resizebox" in line for line in lines):
        lines.append("}")
    lines += ["\\endgroup", "\\end{table}"]
    (GEN / "cost_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    def pick(case, level, column):
        block = df[(df["case"] == case) & (df["level_label"] == level)]
        return float(block[column].iloc[0]) if len(block) else None

    summary["cost_and_sizes"] = {
        "rows": int(len(df)),
        "orthogonal_duct_M0_KKT_over_reference":
            pick("orthogonal_duct", "M0_n200", "KKT_over_reference_unknowns"),
        "orthogonal_duct_M3_KKT_over_reference":
            pick("orthogonal_duct", "M3_n1600", "KKT_over_reference_unknowns"),
        "orthogonal_duct_M5_KKT_over_reference":
            pick("orthogonal_duct", "M5_n6400", "KKT_over_reference_unknowns"),
        "orthogonal_duct_M0_nnz_A": pick("orthogonal_duct", "M0_n200", "nnz_A"),
        "orthogonal_duct_M5_nnz_A": pick("orthogonal_duct", "M5_n6400", "nnz_A"),
        "orthogonal_duct_M0_memory_MiB": pick("orthogonal_duct", "M0_n200", "factor_memory_MiB"),
        "orthogonal_duct_M5_memory_MiB": pick("orthogonal_duct", "M5_n6400", "factor_memory_MiB"),
        "orthogonal_duct_M0_T_cold_s": pick("orthogonal_duct", "M0_n200", "T_cold_s"),
        "orthogonal_duct_M0_T_query_s": pick("orthogonal_duct", "M0_n200", "T_query_s"),
        "orthogonal_duct_M5_T_cold_s": pick("orthogonal_duct", "M5_n6400", "T_cold_s"),
        "orthogonal_duct_M5_T_query_s": pick("orthogonal_duct", "M5_n6400", "T_query_s"),
        "orthogonal_duct_M5_N_system": pick("orthogonal_duct", "M5_n6400", "N_system"),
        "KKT_over_reference_min": float(df["KKT_over_reference_unknowns"].min()),
        "KKT_over_reference_max": float(df["KKT_over_reference_unknowns"].max()),
        "nnz_A_min": int(df["nnz_A"].min()), "nnz_A_max": int(df["nnz_A"].max()),
        "factor_memory_MiB_min": float(df["factor_memory_MiB"].min()),
        "factor_memory_MiB_max": float(df["factor_memory_MiB"].max()),
        "structural_zero_fraction_min": float(df["nnz_A_structural_zero_fraction"].min()),
        "structural_zero_fraction_max": float(df["nnz_A_structural_zero_fraction"].max()),
        "T_cold_s_min": float(df["T_cold_s"].min()), "T_cold_s_max": float(df["T_cold_s"].max()),
        "T_query_s_min": float(df["T_query_s"].min()), "T_query_s_max": float(df["T_query_s"].max()),
        "records": df[["case", "level_label", "N_cv", "N_system", "nnz_A", "nnz_D",
                       "factor_memory_MiB", "reference_total_unknowns",
                       "KKT_over_reference_unknowns", "T_cold_s", "T_query_s"]]
                    .to_dict(orient="records"),
    }
    return df


def self_convergence(summary):
    path = REV / "supplementary/s3_verification" / "self_convergence.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    record = {}
    for case, block in df.groupby("case"):
        block = block.sort_values("N_cv")
        record[case] = {
            "levels": block["level_label"].tolist(),
            "e_u_vs_reference_percent": block["e_u_vs_reference_percent"].tolist(),
            "e_u_vs_finest_level_percent": block["e_u_vs_finest_level_percent"].tolist(),
            "finest_level_vs_reference_percent":
                block["finest_level_vs_reference_percent"].tolist(),
            "reference_steady_converged": bool(block["reference_steady_converged"].iloc[0])
            if pd.notna(block["reference_steady_converged"].iloc[0]) else None,
            "reference_steady_momentum_inf":
                float(block["reference_steady_momentum_inf"].iloc[0])
                if pd.notna(block["reference_steady_momentum_inf"].iloc[0]) else None,
        }
    summary["self_convergence"] = record
    continuation = REV / "supplementary/s3_verification" / "." / "reference_continuation.json"
    if continuation.exists():
        summary["reference_continuation"] = json.loads(
            continuation.read_text(encoding="utf-8")
        )
    return df


def sampled_data(summary):
    path = E24 / "sampled_transfer_rows.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    df = df[df["case"].str.contains("public_berea")].copy()
    df["label"] = df["case"].str.replace("public_berea_", "", regex=False)
    df["label"] = df["label"].str.replace("_localcode", "", regex=False)
    df["ratio"] = df["e_u_trace_moment_percent"] / df["e_u_percent"]
    df = df.sort_values(["trajectory_unique_sites", "state_records"])
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Sampled-velocity reconstruction, before and after the "
        "divergence-constrained projection. \\(e_{u}^{\\rm pre}\\) evaluates the "
        "observed and graph-harmonically completed cell states that define the "
        "target trace; \\(e_{u}^{\\rm post}\\) evaluates \\(\\bm R_i\\bm "
        "z^{\\rm data}\\), the cell velocity of the projected trace. "
        "\\(C_{\\rm obs}\\) is the fraction of cells receiving at least one direct "
        "observation. All rows use the public Berea mask.}",
        "\\label{tab:sampled-pre-post}", "\\begingroup", "\\scriptsize",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{@{}lrrrrrrrr@{}}", "\\toprule",
        "Protocol & \\(N_c\\) & state records & \\(C_{\\rm obs}\\) (\\%) & "
        "completed cells & \\(e_u^{\\rm pre}\\) (\\%) & \\(e_u^{\\rm post}\\) (\\%) & "
        "post/pre & \\(e_K\\) (\\%) \\\\",
        "\\midrule",
    ]
    for _, row in df.iterrows():
        lines.append("%s & %d & %d & %s & %d & %s & %s & %s & %s \\\\" % (
            row["label"].replace("_", "\\_"),
            int(row["trajectory_unique_sites"]), int(row["state_records"]),
            fmt(100.0 * row["directly_measured_cell_fraction"], 2),
            int(row["harmonic_completed_cells"]),
            fmt(row["e_u_percent"], 2), fmt(row["e_u_trace_moment_percent"], 2),
            fmt(row["ratio"], 3), fmt(row["e_K_percent"], 2),
        ))
    lines += ["\\bottomrule", "\\end{tabular}", "}", "\\endgroup", "\\end{table}"]
    (GEN / "sampled_pre_post_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    summary["sampled_data_projection"] = {
        "rows": int(len(df)),
        "ratio_min": float(df["ratio"].min()), "ratio_max": float(df["ratio"].max()),
        "rows_improved": int((df["ratio"] < 1.0).sum()),
        "rows_degraded": int((df["ratio"] >= 1.0).sum()),
        "records": df[["label", "trajectory_unique_sites", "state_records",
                       "directly_measured_cell_fraction", "harmonic_completed_cells",
                       "e_u_percent", "e_u_trace_moment_percent", "ratio",
                       "e_phi_percent", "e_K_percent", "mass_inf_per_volume"]]
                    .to_dict(orient="records"),
    }
    return df


def xptv_measured(summary):
    """The measured X-ray PTV dataset: what it certifies and what it cannot score."""
    path = REV / "table_s8" / "." / "xptv_real_data.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path).sort_values("N_c")
    retention = REV / "table_s8" / "." / "xptv_component_retention.json"
    registration = REV / "table_s8" / "." / "xptv_registration_check.json"

    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Conservative reconstruction from a \\emph{measured} X-ray "
        "particle-tracking dataset (Bultreys et al., 2022). The prescribed-site "
        "count is swept on one fixed \\(96^3\\) block. \\(\\eta_m\\) is the "
        "dimensionless mass backward error of "
        "Equation~\\eqref{eq:mass-backward-error}. The record-level columns score "
        "each held-out record at its own recorded position, against the "
        "leave-one-out within-cell spread (\\(\\varepsilon_{\\mathrm{floor}}\\)), "
        "which no cell-constant state can beat. The Eulerian columns score the "
        "reconstruction against the \\emph{independent} cell means of the held-out "
        "half, on the cells both halves sample; "
        "\\(\\sigma_{\\mathrm{tgt}}\\) is that target's own sampling uncertainty, "
        "obtained by splitting the fitting half again.}",
        "\\label{tab:xptv-measured}", "\\begingroup", "\\scriptsize",
        "\\setlength{\\tabcolsep}{2.0pt}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{@{}rrrrrrrrrrrrr@{}}", "\\toprule",
        " & & & & & & \\multicolumn{2}{c}{Record level (\\%)} & "
        "\\multicolumn{5}{c}{Eulerian, held-out cell means (\\%)} \\\\",
        "\\cmidrule(lr){7-8}\\cmidrule(lr){9-13}",
        "\\(N_s\\) & \\(N_c\\) & \\(\\bar n_r\\) & \\(C_{\\mathrm{obs}}\\) (\\%) & "
        "\\(\\eta_m\\) & \\(\\rho_{\\mathrm{proj}}\\) & "
        "\\(\\varepsilon_{\\mathrm{floor}}\\) & trivial & "
        "cells & \\(\\sigma_{\\mathrm{tgt}}\\) & trivial & pre & post \\\\",
        "\\midrule",
    ]
    for _, row in df.iterrows():
        lines.append(
            "%d & %d & %s & %s & %s & %s & %s & %s & %d & %s & %s & %s & %s \\\\" % (
                int(row["N_sites"]), int(row["N_c"]),
                fmt(row["records_per_cell_mean"], 2),
                fmt(100.0 * row["coverage_fraction"], 1),
                sci(row["mass_backward_error_dimensionless"]),
                fmt(row["projection_correction_relative"], 3),
                fmt(row["within_cell_floor_percent"], 1),
                fmt(row["heldout_error_trivial_mean_percent"], 1),
                int(row["eulerian_cells_sampled_by_both_halves"]),
                fmt(row["eulerian_target_sampling_uncertainty_percent"], 1),
                fmt(row["eulerian_error_trivial_mean_percent"], 1),
                fmt(row["eulerian_error_pre_projection_percent"], 1),
                fmt(row["eulerian_error_post_projection_percent"], 1),
            )
        )
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\endgroup", "\\end{table}"]
    (GEN / "xptv_measured_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )

    resolved = df[df["records_per_cell_mean"] >= 5.0]
    record = {
        "source": path.as_posix(),
        "rows": int(len(df)),
        "N_c": [int(v) for v in df["N_c"]],
        "N_sites": [int(v) for v in df["N_sites"]],
        "records": int(df["records"].iloc[0]),
        "block_size": int(df["block_size"].iloc[0]),
        "records_per_cell_coarsest": float(df["records_per_cell_mean"].iloc[0]),
        "records_per_cell_finest": float(df["records_per_cell_mean"].iloc[-1]),
        "N_c_coarsest": int(df["N_c"].iloc[0]),
        "N_c_finest": int(df["N_c"].iloc[-1]),
        "block_origin_zyx": str(df["block_origin_zyx"].iloc[0]),
        "N_f": int(df["N_f"].iloc[0]),
        "voxel_size_m": float(df["voxel_size_m"].iloc[0]),
        "frame_interval_s": float(df["frame_interval_s"].iloc[0]),
        "citation": str(df["citation"].iloc[0]),
        "eta_m_min": float(df["mass_backward_error_dimensionless"].min()),
        "eta_m_max": float(df["mass_backward_error_dimensionless"].max()),
        "projection_correction_min": float(df["projection_correction_relative"].min()),
        "projection_correction_max": float(df["projection_correction_relative"].max()),
        "within_cell_floor_min": float(df["within_cell_floor_percent"].min()),
        "within_cell_floor_max": float(df["within_cell_floor_percent"].max()),
        "record_trivial_percent": float(df["heldout_error_trivial_mean_percent"].iloc[0]),
        "eulerian_target_noise_min": float(
            df["eulerian_target_sampling_uncertainty_percent"].min()),
        "eulerian_target_noise_max": float(
            df["eulerian_target_sampling_uncertainty_percent"].max()),
        "resolved_rows": int(len(resolved)),
        "resolved_min_records_per_cell": 5.0,
        "resolved_pre_beats_trivial": int(
            (resolved["eulerian_error_pre_projection_percent"]
             < resolved["eulerian_error_trivial_mean_percent"]).sum()),
        "resolved_post_worse_than_pre": int(
            (resolved["eulerian_error_post_projection_percent"]
             > resolved["eulerian_error_pre_projection_percent"]).sum()),
        "resolved_post_minus_pre_min": float(
            (resolved["eulerian_error_post_projection_percent"]
             - resolved["eulerian_error_pre_projection_percent"]).min()),
        "resolved_post_minus_pre_max": float(
            (resolved["eulerian_error_post_projection_percent"]
             - resolved["eulerian_error_pre_projection_percent"]).max()),
    }
    window = REV / "table_s8" / "." / "xptv_measured_window.csv"
    if window.exists():
        record["tracked_particles"] = int(
            pd.read_csv(window, usecols=["particle_id"])["particle_id"].nunique())
    if retention.exists():
        retained = json.loads(retention.read_text(encoding="utf-8"))
        record["component_retention"] = retained
        record["block_porosity"] = (
            float(retained["pore_voxels_before"]) / float(record["block_size"]) ** 3)
    if registration.exists():
        record["registration"] = json.loads(registration.read_text(encoding="utf-8"))
    field_reg = REV / "table_s8" / "." / "xptv_field_registration.json"
    if field_reg.exists():
        loaded = json.loads(field_reg.read_text(encoding="utf-8"))
        axes = {int(entry["field_axis"]): entry for entry in loaded["per_axis"]}
        record["field_registration"] = {
            "axes_that_register": loaded["axes_that_register"],
            "voxelwise_overlap_ratio_over_chance":
                loaded["voxelwise_overlap_ratio_over_chance"],
            "crop_shape_matches_field": loaded["crop_shape_matches_field"],
            "flow_axis_rescaled_r": axes[0]["rescaled_best"]["r"],
            "flow_axis_control_r": axes[0]["rescaled_control"]["r"],
            "transverse_axis_r": axes[1]["rescaled_best"]["r"],
            "transverse_control_r": axes[1]["rescaled_control"]["r"],
            "conclusion": loaded["conclusion"],
        }
    summary["xptv_measured"] = record
    return df


def trace_degeneracy(summary):
    """How much sharing does the shared trace actually achieve?

    The formulation's distinguishing object is a velocity trace shared between
    two cells across a connected interface patch, carrying a constant and, where
    the patch supports it, tangential linear modes.  Whether that sharing is
    realised is a measurement, not a definition, and the per-run records already
    carry every quantity needed: the number of cell-pair interfaces, the
    facelets on them, the connected patches they fragment into, and the modes
    that survive the variance-based pruning.  The ratio that matters is modes
    per facelet: at 1.0 the trace carries one vector per voxel face and shares
    nothing.
    """
    frame = ladder_frame()
    if frame is None:
        return None
    order = {"orthogonal_duct": 0, "skewed_duct": 1, "bentheimer_crop": 2}
    needed = {"N_edges", "N_connected_patches", "N_interface_facelets", "N_trace_modes"}
    if not needed.issubset(frame.columns):
        return None
    df = frame.assign(_o=frame["case"].map(order).fillna(9)).sort_values(["_o", "N_cv"])
    df = df.assign(
        facelets_per_edge=df["N_interface_facelets"] / df["N_edges"],
        patches_per_edge=df["N_connected_patches"] / df["N_edges"],
        facelets_per_patch=df["N_interface_facelets"] / df["N_connected_patches"],
        modes_per_patch=df["N_trace_modes"] / df["N_connected_patches"],
        modes_per_facelet=df["N_trace_modes"] / df["N_interface_facelets"],
    )
    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{How much sharing the shared trace achieves, along the three "
        "controlled refinement families.  A cell-pair interface carries "
        "\\(N_{\\rm fl}/N_e\\) facelets; it fragments into \\(N_p/N_e\\) "
        "face-connected patches; each patch holds \\(N_{\\rm fl}/N_p\\) facelets "
        "and retains \\(N_m/N_p\\) modes after the variance pruning.  The last "
        "column is the ratio that decides the cost and the coupling: at "
        "\\(N_m/N_{\\rm fl}=1\\) the trace carries one vector per voxel face and "
        "shares nothing between cells.}",
        "\\label{tab:trace-degeneracy}", "\\begingroup", "\\scriptsize",
        "\\setlength{\\tabcolsep}{3.0pt}",
        "\\begin{tabular}{@{}llrrrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & \\(H_g/h\\) & \\(N_{\\rm fl}/N_e\\) & "
        "\\(N_p/N_e\\) & \\(N_{\\rm fl}/N_p\\) & \\(N_m/N_p\\) & "
        "\\(N_m/N_{\\rm fl}\\) & \\(e_u\\) (\\%) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            lines.append("%s & %s & %d & %s & %s & %s & %s & %s & %s & %s \\\\" % (
                CASE_DISPLAY.get(case, case), str(row["level_label"]).split("_")[0],
                int(row["N_cv"]), fmt(row.get("h_S_over_h"), 0),
                fmt(row["facelets_per_edge"], 2), fmt(row["patches_per_edge"], 2),
                fmt(row["facelets_per_patch"], 3), fmt(row["modes_per_patch"], 3),
                fmt(row["modes_per_facelet"], 3), fmt(row["e_u_percent"], 2),
            ))
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "trace_degeneracy_table.tex").write_text(
        HEADER % "reproduce/figure_06/refinement/runs/*/*/row.json" + "\n".join(lines) + "\n",
        encoding="utf-8",
    )
    record = {
        "rows": int(len(df)),
        "modes_per_facelet_min": float(df["modes_per_facelet"].min()),
        "modes_per_facelet_max": float(df["modes_per_facelet"].max()),
        "facelets_per_patch_min": float(df["facelets_per_patch"].min()),
        "facelets_per_patch_max": float(df["facelets_per_patch"].max()),
        "patches_per_edge_min": float(df["patches_per_edge"].min()),
        "patches_per_edge_max": float(df["patches_per_edge"].max()),
        "facelets_per_edge_min": float(df["facelets_per_edge"].min()),
        "facelets_per_edge_max": float(df["facelets_per_edge"].max()),
        "modes_per_patch_min": float(df["modes_per_patch"].min()),
        "modes_per_patch_max": float(df["modes_per_patch"].max()),
        "rows_above_0p99_modes_per_facelet": int((df["modes_per_facelet"] > 0.99).sum()),
    }
    df = df.assign(
        interface_basis_vector_dofs=9 * df["N_edges"],
        interface_basis_reduction=df["N_trace_vector_dofs"] / (9 * df["N_edges"]),
    )
    for case, block in df.groupby("case"):
        block = block.sort_values("N_cv")
        record.setdefault(case, {})["interface_basis_reduction"] = (
            block["interface_basis_reduction"].tolist())
    at_four = df[df["h_S_over_h"] == 4.0]
    if len(at_four):
        record["modes_per_facelet_at_Hh4_min"] = float(at_four["modes_per_facelet"].min())
        record["modes_per_facelet_at_Hh4_families"] = int(at_four["case"].nunique())
    record["interface_basis_reduction_coarsest_max"] = float(
        df.sort_values("N_cv").groupby("case").first()["interface_basis_reduction"].max())
    record["interface_basis_reduction_finest_min"] = float(
        df.sort_values("N_cv").groupby("case").last()["interface_basis_reduction"].min())
    record["levels_where_interface_basis_costs_more"] = int(
        (df["interface_basis_reduction"] < 1.0).sum())
    coarsest = df[df["case"] == "bentheimer_crop"].sort_values("N_cv").iloc[0]
    record["bentheimer_M0_edges"] = int(coarsest["N_edges"])
    record["bentheimer_M0_modes_assembled"] = int(coarsest["N_trace_modes"])
    record["bentheimer_M0_modes_if_three_per_interface"] = 3 * int(coarsest["N_edges"])
    for case, block in df.groupby("case"):
        block = block.sort_values("N_cv")
        record.setdefault(case, {}).update({
            "N_cv": block["N_cv"].tolist(),
            "modes_per_facelet": block["modes_per_facelet"].tolist(),
            "facelets_per_edge": block["facelets_per_edge"].tolist(),
        })
    summary["trace_degeneracy"] = record
    return df


def repeated_query(summary):
    """Does a factorizing solver change the repeated-query balance?

    Two reusing solvers are available in the code, and both are run here
    across the refinement family.  A solver that cannot be built at a given size is not a
    missing row: affordability is the measurement, so the failure and its
    exception are tabulated beside the timings.
    """
    paths = [REV / "supplementary/s4_cost" / "repeated_query_cost_M5_minres.csv",
             REV / "supplementary/s4_cost" / "_factorized" / "repeated_query_cost.csv",
             REV / "supplementary/s4_cost" / "repeated_query_cost.csv"]
    frames = [pd.read_csv(p) for p in paths if p.exists()]
    if not frames:
        return None
    df = pd.concat(frames, ignore_index=True).drop_duplicates(
        subset=["case", "level_label", "solver"], keep="first")
    solver_order = {"minres": 0, "schur_cg": 1, "direct_lu": 2}
    df = df.assign(
        _l=df["level_label"].str.extract(r"M(\d+)")[0].astype(int),
        _s=df["solver"].map(solver_order).fillna(9),
    ).sort_values(["_l", "_s"])

    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Repeated-query cost, and whether a factorizing solver is "
        "affordable. \\(T_{\\rm cold}\\) includes construction, assembly, "
        "factorization and one solve; \\(T_{\\rm query}\\) is the median of the "
        "remaining solves for further forcings on the frozen complex. A solver "
        "that could not be built is reported with the exception it raised, "
        "because affordability at a given algebraic size is one of the "
        "measurements rather than a gap in the table.}",
        "\\label{tab:repeated-query}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}llrrrrrl@{}}", "\\toprule",
        "Level & Solver & \\(N_{\\rm sys}\\) & \\(T_{\\rm cold}\\) (s) & "
        "\\(T_{\\rm query}\\) (s) & ratio & factor (MiB) & outcome \\\\",
        "\\midrule",
    ]
    for _, row in df.iterrows():
        ok = str(row.get("status")) == "ok"
        lines.append("%s & \\texttt{%s} & %d & %s & %s & %s & %s & %s \\\\" % (
            str(row["level_label"]).split("_")[0],
            str(row["solver"]).replace("_", "\\_"), int(row["N_system"]),
            fmt(row.get("T_cold_s"), 1) if ok else "--",
            fmt(row.get("T_query_s"), 1) if ok else "--",
            fmt(row.get("query_over_cold"), 3) if ok else "--",
            fmt(row.get("factor_memory_MiB"), 0) if ok else "--",
            "ok" if ok else "\\texttt{%s}" % str(row.get("exception_type", "failed")),
        ))
    lines += ["\\bottomrule", "\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "repeated_query_table.tex").write_text(
        HEADER % "; ".join(p.as_posix() for p in paths if p.exists())
        + "\n".join(lines) + "\n", encoding="utf-8"
    )

    ok = df[df["status"] == "ok"]
    failed = df[df["status"] != "ok"]
    record = {
        "rows": int(len(df)),
        "solvers": sorted(set(df["solver"])),
        "levels": sorted(set(df["level_label"])),
        "factorizing_attempts": int((df["solver"] != "minres").sum()),
        "factorizing_failures": int((failed["solver"] != "minres").sum()),
        "failure_exception_types": sorted(set(
            str(v) for v in failed.get("exception_type", pd.Series(dtype=object)).dropna())),
    }
    for _, row in ok.iterrows():
        record["%s__%s" % (row["level_label"], row["solver"])] = {
            "N_system": int(row["N_system"]),
            "T_cold_s": float(row["T_cold_s"]),
            "T_query_s": float(row["T_query_s"]),
            "query_over_cold": float(row["query_over_cold"]),
            "factor_memory_MiB": float(row["factor_memory_MiB"]),
            "iterations_median": int(row["linear_solver_iterations_median"]),
        }
    for _, row in failed.iterrows():
        record["%s__%s" % (row["level_label"], row["solver"])] = {
            "N_system": int(row["N_system"]),
            "status": "failed",
            "exception_type": str(row.get("exception_type")),
        }
    summary["repeated_query"] = record
    return df


def velocity_distribution(summary):
    """The observable a velocity field should be scored on, if the field is the product."""
    path = REV / "supplementary/s3_verification" / "velocity_distribution.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    order = {"orthogonal_duct": 0, "skewed_duct": 1, "bentheimer_crop": 2}
    df = df.assign(
        _o=df["case"].map(order).fillna(9),
        _l=df["level_label"].str.extract(r"M(\d+)")[0].astype(int),
    ).sort_values(["_o", "_l"])

    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Distribution of the axial cell velocity, method against "
        "reference, on the three controlled refinement families. \\(W_1\\) is the "
        "volume-weighted Wasserstein-1 distance between the two distributions "
        "divided by the reference mean, so it is dimensionless. The back-flow "
        "columns give the volume fraction carrying negative axial velocity, a "
        "recirculation measure that an \\(L^2\\) norm barely sees. \\(e_u\\) is "
        "repeated from Table~\\ref{tab:controlled-refinement} because the two "
        "observables do not move together.}",
        "\\label{tab:velocity-distribution}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}llrrrrrr@{}}", "\\toprule",
        "Case & Level & \\(N_c\\) & \\(H_g/h\\) & \\(W_1/\\bar u\\) & "
        "back-flow (\\%) & reference (\\%) & \\(e_u\\) (\\%) \\\\",
        "\\midrule",
    ]
    for case, block in df.groupby("case", sort=False):
        for _, row in block.iterrows():
            lines.append("%s & %s & %d & %s & %s & %s & %s & %s \\\\" % (
                CASE_DISPLAY.get(case, case), str(row["level_label"]).split("_")[0],
                int(row["N_cv"]), fmt(row.get("h_S_over_h"), 0),
                fmt(row["w1_over_mean"], 4),
                fmt(row["backflow_volume_fraction_percent"], 2),
                fmt(row["backflow_volume_fraction_reference_percent"], 2),
                fmt(row["e_u_percent"], 2),
            ))
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines += ["\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "velocity_distribution_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )

    record = {"rows": int(len(df)), "source": path.as_posix()}
    for case, block in df.groupby("case"):
        block = block.sort_values("_l")
        w1 = block["w1_over_mean"].tolist()
        record[case] = {
            "w1_over_mean": w1,
            "w1_coarsest": float(w1[0]),
            "w1_finest": float(w1[-1]),
            "w1_best": float(min(w1)),
            "w1_monotone_decreasing": bool(
                all(b < a for a, b in zip(w1, w1[1:]))),
            "backflow_percent": block["backflow_volume_fraction_percent"].tolist(),
            "backflow_reference_percent":
                block["backflow_volume_fraction_reference_percent"].tolist(),
            "backflow_coarsest": float(block["backflow_volume_fraction_percent"].iloc[0]),
            "backflow_reference_coarsest":
                float(block["backflow_volume_fraction_reference_percent"].iloc[0]),
            "backflow_finest": float(block["backflow_volume_fraction_percent"].iloc[-1]),
            "backflow_reference_finest":
                float(block["backflow_volume_fraction_reference_percent"].iloc[-1]),
        }
    record["w1_monotone_families"] = int(sum(
        1 for c in order if c in record and record[c]["w1_monotone_decreasing"]))
    record["families"] = int(df["case"].nunique())
    summary["velocity_distribution"] = record
    return df


def permeability_definition(summary):
    """The two sides of e_K are formed by different functionals; measure the offset."""
    path = REV / "supplementary/s2_discretization" / "permeability_readouts.json"
    if not path.exists():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    report, rows = payload["summary"], payload["rows"]
    references = [r for r in rows if r["kind"] == "reference"]
    runs = [r for r in rows if r["kind"] == "run"]
    references.sort(key=lambda r: r["definition_offset_percent"])

    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{The permeability error compares two different functionals. The "
        "method forms \\(K\\) from the face fluxes; the reference value stored in "
        "each archived field, which the loader passes through unchanged, is the "
        "volume-weighted mean velocity, verified here on every reference "
        "available. On a continuum incompressible field the two agree; on a "
        "discrete one they differ, and the difference enters every reported "
        "\\(e_K\\) as a case-dependent systematic term.}",
        "\\label{tab:permeability-definition}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
        "Reference & cells & \\(K\\) from fluxes & \\(K\\) stored & offset (\\%) \\\\",
        "\\midrule",
    ]
    for row in references:
        lines.append("\\texttt{%s} & %d & %s & %s & %s \\\\" % (
            str(row["case"]).replace("_", "\\_"), int(row["cells"]),
            "%.6g" % row["K_flux"], "%.6g" % row["K_stored"],
            fmt(row["definition_offset_percent"], 3),
        ))
    lines += ["\\bottomrule", "\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "permeability_definition_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )

    record = dict(report)
    worst = max(runs, key=lambda r: abs(r["shift_percentage_points"])) if runs else None
    if worst is not None:
        record["worst_shift_case"] = worst["case"]
        record["worst_shift_level"] = worst["level_label"]
        record["worst_shift_as_reported"] = worst["e_K_as_reported_percent"]
        record["worst_shift_consistent"] = worst["e_K_consistent_percent"]
    for row in runs:
        record["%s__%s" % (row["case"], row["level_label"])] = {
            "e_K_as_reported_percent": row["e_K_as_reported_percent"],
            "e_K_consistent_percent": row["e_K_consistent_percent"],
            "shift_percentage_points": row["shift_percentage_points"],
        }
    bent = [r for r in runs if r["case"] == "bentheimer_crop"]
    if bent:
        record["bentheimer_offset_percent"] = float(
            [r for r in references if r["case"] == "bentheimer_crop"][0]
            ["definition_offset_percent"])
        record["bentheimer_runs_below_offset_as_reported"] = int(sum(
            1 for r in bent
            if r["e_K_as_reported_percent"] < record["bentheimer_offset_percent"]))
    summary["permeability_definition"] = record
    return references


def cost_scaling_law(summary):
    """Reducing cells does not reduce work, and the exponents say why.

    The unknowns of this formulation live on the interface facelets, not on the
    cells.  Total interfacial area of a partition into N_c cells of a fixed
    domain grows as N_c^{1/3}, so the unknown count follows that law rather than
    N_c.  The nonzero count runs the other way: coarsening puts more trace modes
    on each cell, the local block grows as the square of that number, and the
    product beats the reduction in cell count.  Both exponents are fitted here on
    each family so the statement is a measurement rather than a scaling argument.
    """
    path = REV / "supplementary/s4_cost" / "cost_and_sizes.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    needed = {"case", "N_cv", "N_interface_facelets", "N_system", "nnz_KKT"}
    if not needed.issubset(df.columns):
        return None
    order = {"orthogonal_duct": 0, "skewed_duct": 1, "bentheimer_crop": 2}

    def exponent(x, y):
        lx, ly = np.log(np.asarray(x, float)), np.log(np.asarray(y, float))
        slope, _ = np.polyfit(lx, ly, 1)
        return float(slope), float(np.corrcoef(lx, ly)[0, 1])

    lines = [
        "\\begin{table}[t]", "\\centering",
        "\\caption{Why coarsening does not reduce the work. Fitted power laws in "
        "the control-volume count along each controlled refinement family. The "
        "unknowns sit on interface facelets, whose total number follows the "
        "surface-to-volume law \\(N_c^{1/3}\\); the nonzero count carries the "
        "opposite sign, because a coarser cell carries more trace modes and its "
        "local block grows as the square of that number. \\(R\\) is the "
        "correlation of the fit in log--log.}",
        "\\label{tab:cost-scaling-law}", "\\begingroup", "\\scriptsize",
        "\\begin{tabular}{@{}lrrrrrr@{}}", "\\toprule",
        " & \\multicolumn{2}{c}{\\(N_{\\rm fl}\\)} & "
        "\\multicolumn{2}{c}{\\(N_{\\rm sys}\\)} & "
        "\\multicolumn{2}{c}{\\(\\mathrm{nnz}\\)} \\\\",
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}",
        "Case & exponent & \\(R\\) & exponent & \\(R\\) & exponent & \\(R\\) \\\\",
        "\\midrule",
    ]
    record = {"surface_law_exponent": 1.0 / 3.0}
    for case in sorted(set(df["case"]), key=lambda c: order.get(c, 9)):
        block = df[df["case"] == case].sort_values("N_cv")
        if len(block) < 4:
            continue
        entry = {}
        cells = block["N_cv"]
        for key, column in (("facelets", "N_interface_facelets"),
                            ("system", "N_system"), ("nnz", "nnz_KKT")):
            slope, correlation = exponent(cells, block[column])
            entry[key + "_exponent"] = slope
            entry[key + "_correlation"] = correlation
        entry["nnz_per_row_coarsest"] = float(
            block["nnz_KKT"].iloc[0] / block["N_system"].iloc[0])
        entry["nnz_per_row_finest"] = float(
            block["nnz_KKT"].iloc[-1] / block["N_system"].iloc[-1])
        entry["nnz_coarsest_over_finest"] = float(
            block["nnz_KKT"].iloc[0] / block["nnz_KKT"].iloc[-1])
        entry["cells_ratio"] = float(block["N_cv"].iloc[-1] / block["N_cv"].iloc[0])
        entry["system_ratio"] = float(block["N_system"].iloc[-1] / block["N_system"].iloc[0])
        record[case] = entry
        lines.append("%s & %s & %s & %s & %s & %s & %s \\\\" % (
            CASE_DISPLAY.get(case, case),
            fmt(entry["facelets_exponent"], 3), fmt(entry["facelets_correlation"], 4),
            fmt(entry["system_exponent"], 3), fmt(entry["system_correlation"], 4),
            fmt(entry["nnz_exponent"], 3), fmt(entry["nnz_correlation"], 4),
        ))
    lines += ["\\bottomrule", "\\end{tabular}", "\\endgroup", "\\end{table}"]
    (GEN / "cost_scaling_law_table.tex").write_text(
        HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8"
    )
    families = [record[c] for c in order if c in record]
    if families:
        record["facelet_exponent_min"] = min(f["facelets_exponent"] for f in families)
        record["facelet_exponent_max"] = max(f["facelets_exponent"] for f in families)
        record["nnz_exponent_min"] = min(f["nnz_exponent"] for f in families)
        record["nnz_exponent_max"] = max(f["nnz_exponent"] for f in families)
        record["families_with_negative_nnz_exponent"] = int(sum(
            1 for f in families if f["nnz_exponent"] < 0.0))
        record["families"] = len(families)
    summary["cost_scaling_law"] = record
    return record


def roi_exactness(summary):
    path = REV / "supplementary/s1_ownership" / "roi_freespace_exactness.json"
    if not path.exists():
        return None
    data = json.loads(path.read_text(encoding="utf-8"))
    summary["roi_freespace_exactness"] = {
        "status": data["status"],
        "backends": {
            name: {
                "status": report["status"], "cases": report["cases"],
                "distance_mismatch": report["distance_mismatch"],
                "owner_mismatch": report["owner_mismatch"],
                "tie_mismatch": report["tie_mismatch"],
                "tie_voxels": report["tie_voxels"],
            }
            for name, report in data["backends"].items()
        },
        "exhaustive_1d_length": data["exhaustive_1d_length"],
    }
    return data



def canonical(summary):
    """Generate the headline cells from a CSV, and signs from K/K_ref in the run records."""
    path = PROJECT / "data/controlled_cases/expected/table_source_values.csv"
    df = pd.read_csv(path)
    names = {"thin_wall": "Thin-wall case", "narrow_throat": "Narrow-throat case", "maze": "Maze case"}
    records = []
    lines = [r"\begin{table}[t]", r"\centering",
             r"\caption{Same-flow verification of the shared-trace Stokes branch. The reference flow generates both the trajectory sites and the comparison field; these are not independent forward-validation cases. The permeability column is the signed discrepancy \(e_K^{\rm s}\), whereas the flux and cell-mean columns are non-negative relative discrepancies.}",
             r"\label{tab:final-accuracy-cost}", r"\begingroup", r"\scriptsize",
             r"\setlength{\tabcolsep}{3.2pt}", r"\resizebox{\textwidth}{!}{%",
             r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
             r"Case & \(N_c\) & \(e_K^{\rm s}\) (\%) & \(e_\phi\) (\%) & \(e_{u,\mathrm{cell}}^{\mathrm{solve}}\) (\%) & \(r_\infty^m\) \\", r"\midrule"]
    for _, row in df.iterrows():
        case = row["case"]
        manifest = PROJECT / "data/controlled_cases" / (case + "/run_record.json")
        m = json.loads(manifest.read_text(encoding="utf-8"))["row"]
        signed = 100 * (m["K_eff_x"] - m["K_ref_x"]) / abs(m["K_ref_x"])
        if not math.isclose(abs(signed), row["e_K_percent"], abs_tol=1e-10):
            raise ValueError(f"CSV/manifest disagreement: {case}")
        lines.append("%s & %d & %.2f & %.2f & %.2f & %s \\\\" % (
            names.get(case, CASE_DISPLAY.get(case, case)), int(row["N_c"]), signed,
            row["e_phi_percent"], row["e_u_percent"], sci(row["mass_inf_per_volume"])))
        records.append({"case":case, "e_K_signed_percent":signed,
                        "e_phi_percent":float(row["e_phi_percent"]), "e_u_percent":float(row["e_u_percent"]),
                        "K":m["K_eff_x"], "K_ref":m["K_ref_x"],
                        "manifest":manifest.relative_to(PROJECT).as_posix()})
    lines += [r"\bottomrule", r"\end{tabular}%", "}", r"\endgroup", r"\end{table}"]
    (GEN/"final_accuracy_cost_table.tex").write_text(HEADER % path.relative_to(PROJECT).as_posix() + "\n".join(lines) + "\n", encoding="utf-8")
    summary["canonical_same_flow"] = records
    return df

GENERATORS = (
        ("canonical", canonical),
        ("controlled_refinement", controlled_refinement),
        ("mass_backward_error", mass_backward_error),
        ("manufactured", manufactured),
        ("manufactured_fixed_h", manufactured_fixed_h),
        ("fibrous", fibrous),
        ("euclidean", euclidean),
        ("site_sources", site_sources),
        ("kernel_exact", kernel_exact),
        ("stability", stability),
        ("stability_ladder", stability_ladder),
        ("stabilization_scale", stabilization_scale),
        ("cost", cost),
        ("self_convergence", self_convergence),
        ("sampled_data", sampled_data),
        ("xptv_measured", xptv_measured),
        ("trace_degeneracy", trace_degeneracy),
        ("repeated_query", repeated_query),
    ("velocity_distribution", velocity_distribution),
    ("permeability_definition", permeability_definition),
    ("cost_scaling_law", cost_scaling_law),
        ("roi_exactness", roi_exactness),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(REV / "../outputs/tables"))
    parser.add_argument("--only", nargs="+", choices=[name for name, _ in GENERATORS])
    args = parser.parse_args()
    GEN.mkdir(parents=True, exist_ok=True)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    summary = json.loads((PROJECT / "outputs/results_summary.json").read_text(encoding="utf-8")) if args.only else {"protocol_id": "pvfv_tables"}
    produced = []
    for name, function in GENERATORS:
        if args.only and name not in args.only:
            continue
        result = function(summary)
        produced.append((name, result is not None))
        print("  %-24s %s" % (name, "written" if result is not None else "SOURCE MISSING"))

    (out / "results_summary.json").write_text(
        json.dumps(summary, indent=2, default=float), encoding="utf-8"
    )
    (PROJECT / "outputs/results_summary.json").write_text(
        json.dumps(summary, indent=2, default=float), encoding="utf-8"
    )
    print("[write] " + str(out / "results_summary.json"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
